name: SimplePapiAPI
version: '1.0-SNAPSHOT'
main: com.whitelu.simplepapiapi.SimplePapiAPI
api-version: '1.13'
depend: [PlaceholderAPI]
authors: [whitelu, KojiTadokoro]
description: A simple HTTP API for PlaceholderAPI variables
commands:
  simplepapiapi:
    aliases:
      - spp
    permission: simplepapiapi.admin